# Generated by Django 2.2 on 2024-11-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
