# Generated by Django 2.2 on 2024-11-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_movie_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tags',
            new_name='movie_tags',
        ),
    ]
