# Generated by Django 2.2 on 2024-11-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20241121_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_tags',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
